apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/sh", "-c", "sleep 3600"]
